x = open("text4.txt","w")
x.write("hai ")
x.close()
x = open("text4.txt","rt")
print(x.read())
x.close()
x = open("text4.txt","a")
x.write("how are you")
x.close()
x = open("text4.txt","rt")
print(x.read())
x.close()
